# Generated by Django 3.2.1 on 2022-01-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=10, null=True)),
                ('author_last', models.CharField(default=None, max_length=10, null=True)),
                ('author_first', models.CharField(default=None, max_length=10, null=True)),
                ('author_link', models.CharField(default=None, max_length=10, null=True)),
                ('editor', models.CharField(default=None, max_length=10, null=True)),
                ('editor_last', models.CharField(default=None, max_length=10, null=True)),
                ('editor_first', models.CharField(default=None, max_length=10, null=True)),
                ('editor_link', models.CharField(default=None, max_length=10, null=True)),
                ('publication_date', models.CharField(default=None, max_length=20, null=True)),
                ('date', models.CharField(default=None, max_length=10, null=True)),
                ('year', models.CharField(default=None, max_length=10, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('chapter', models.CharField(default=None, max_length=10, null=True)),
                ('type', models.CharField(default=None, max_length=10, null=True)),
                ('work', models.CharField(default=None, max_length=10, null=True)),
                ('edition', models.CharField(default=None, max_length=10, null=True)),
                ('series', models.CharField(default=None, max_length=10, null=True)),
                ('volume', models.CharField(default=None, max_length=10, null=True)),
                ('issue', models.CharField(default=None, max_length=10, null=True)),
                ('publisher', models.CharField(default=None, max_length=10, null=True)),
                ('page', models.CharField(default=None, max_length=10, null=True)),
                ('pages', models.CharField(default=None, max_length=10, null=True)),
                ('no_pp', models.CharField(default=None, max_length=10, null=True)),
                ('isbn', models.CharField(default=None, max_length=20, null=True)),
                ('issn', models.CharField(default=None, max_length=20, null=True)),
                ('doi', models.CharField(default=None, max_length=50, null=True)),
                ('url', models.URLField(default=None, null=True)),
                ('access_date', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=None, max_length=100)),
                ('wikislug', models.SlugField(default=None, max_length=255, null=True)),
                ('url', models.URLField(default=None, null=True)),
                ('notes', models.TextField(default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Heritage Site Type')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.heritagesite', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, verbose_name='Topic Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Topic Type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maps.topic')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
    ]
