# Generated by Django 3.2.1 on 2021-05-09 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210506_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkAdminBoundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('ctyua19cd', models.TextField(blank=True, null=True)),
                ('ctyua19nm', models.TextField(blank=True, null=True)),
                ('ctyua19nmw', models.TextField(blank=True, null=True)),
                ('bng_e', models.BigIntegerField(blank=True, null=True)),
                ('bng_n', models.BigIntegerField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('st_areasha', models.FloatField(blank=True, null=True)),
                ('st_lengths', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'UK_admin_boundaries',
                'managed': True,
            },
        ),
    ]
