# Generated by Django 3.2.1 on 2021-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_ukadminboundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdukalwaysopenland',
            name='mynotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukalwaysopenland',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gduklistedbuildings',
            name='mynotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gduklistedbuildings',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukparksgardens',
            name='mynotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukparksgardens',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukscheduledmonuments',
            name='mynotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukscheduledmonuments',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukworldheritagesites',
            name='mynotes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gdukworldheritagesites',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='hyperlink',
            field=models.URLField(blank=True, db_column='Hyperlink', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='hyperlink',
            field=models.URLField(blank=True, db_column='Hyperlink', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='hyperlink',
            field=models.URLField(blank=True, db_column='Hyperlink', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='hyperlink',
            field=models.URLField(blank=True, db_column='Hyperlink', max_length=300, null=True),
        ),
    ]
