# Generated by Django 3.2.1 on 2022-02-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_profile'),
        ('maps', '0004_alter_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritagesite',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='tpam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Heritage Site Type'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
