# Generated by Django 3.2.1 on 2021-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20210509_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdukalwaysopenland',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='amenddate',
            field=models.CharField(blank=True, db_column='AmendDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='grade',
            field=models.CharField(blank=True, db_column='Grade', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='legacyuid',
            field=models.CharField(blank=True, db_column='LegacyUID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='listdate',
            field=models.CharField(blank=True, db_column='ListDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gduklistedbuildings',
            name='ngr',
            field=models.CharField(blank=True, db_column='NGR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='amenddate',
            field=models.CharField(blank=True, db_column='AmendDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='grade',
            field=models.CharField(blank=True, db_column='Grade', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='legacyuid',
            field=models.CharField(blank=True, db_column='LegacyUID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='ngr',
            field=models.CharField(blank=True, db_column='NGR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='regdate',
            field=models.CharField(blank=True, db_column='RegDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='amenddate',
            field=models.CharField(blank=True, db_column='AmendDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='legacyuid',
            field=models.CharField(blank=True, db_column='LegacyUID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='ngr',
            field=models.CharField(blank=True, db_column='NGR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='scheddate',
            field=models.CharField(blank=True, db_column='SchedDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='amenddate',
            field=models.CharField(blank=True, db_column='AmendDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='inscrdate',
            field=models.CharField(blank=True, db_column='InscrDate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='legacyuid',
            field=models.CharField(blank=True, db_column='LegacyUID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='ngr',
            field=models.CharField(blank=True, db_column='NGR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdukworldheritagesites',
            name='notes',
            field=models.CharField(blank=True, db_column='Notes', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ukadminboundaries',
            name='ctyua19cd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ukadminboundaries',
            name='ctyua19nm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ukadminboundaries',
            name='ctyua19nmw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
