# Generated by Django 3.2.1 on 2022-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20220228_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='work',
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
