# Generated by Django 3.2.1 on 2021-05-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0005_auto_20210512_1132'),
        ('maps', '0006_entry_reference_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Topic Type'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Reference Type'),
        ),
    ]
