# Generated by Django 3.2.1 on 2022-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20220502_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
