# Generated by Django 3.2.1 on 2022-05-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20220503_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(default=1398, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.heritagesite', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, default=None),
        ),
    ]
