# Generated by Django 3.2.1 on 2021-05-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0005_auto_20210512_1132'),
        ('maps', '0007_auto_20210512_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=None, max_length=100)),
                ('wikislug', models.SlugField(default=None, max_length=255, null=True)),
                ('url', models.URLField(default=None, null=True)),
                ('notes', models.TextField(default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Heritage Site Type')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.heritagesite', verbose_name='Location')),
            ],
        ),
    ]
