# Generated by Django 3.2.1 on 2021-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20210514_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=25, verbose_name='Topic Name'),
        ),
    ]
