# Generated by Django 3.2.1 on 2023-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=9999),
        ),
    ]
