# Generated by Django 3.2.1 on 2021-06-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_topic_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
