# Generated by Django 3.2.1 on 2021-09-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0012_auto_20210626_1621'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='GdUkAlwaysOpenLand',
        # ),
        # migrations.DeleteModel(
        #     name='GdUkListedBuildings',
        # ),
        # migrations.DeleteModel(
        #     name='GdUkParksGardens',
        # ),
        # migrations.DeleteModel(
        #     name='GdUkScheduledMonuments',
        # ),
        # migrations.DeleteModel(
        #     name='GdUkWorldHeritageSites',
        # ),
        # migrations.RemoveField(
        #     model_name='reference',
        #     name='owner',
        # ),
        # migrations.RemoveField(
        #     model_name='reference',
        #     name='type',
        # ),
        # migrations.DeleteModel(
        #     name='Shop',
        # ),
        # migrations.DeleteModel(
        #     name='UkAdminBoundaries',
        # ),
        # migrations.AlterField(
        #     model_name='post',
        #     name='owner',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.DeleteModel(
        #     name='Reference',
        # ),
    ]
