# Generated by Django 3.2.1 on 2021-10-25 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0013_auto_20210907_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=10, null=True)),
                ('author_last', models.CharField(default=None, max_length=10, null=True)),
                ('author_first', models.CharField(default=None, max_length=10, null=True)),
                ('author_link', models.CharField(default=None, max_length=10, null=True)),
                ('editor', models.CharField(default=None, max_length=10, null=True)),
                ('editor_last', models.CharField(default=None, max_length=10, null=True)),
                ('editor_first', models.CharField(default=None, max_length=10, null=True)),
                ('editor_link', models.CharField(default=None, max_length=10, null=True)),
                ('publication_date', models.CharField(default=None, max_length=20, null=True)),
                ('date', models.CharField(default=None, max_length=10, null=True)),
                ('year', models.CharField(default=None, max_length=10, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('chapter', models.CharField(default=None, max_length=10, null=True)),
                ('type', models.CharField(default=None, max_length=10, null=True)),
                ('work', models.CharField(default=None, max_length=10, null=True)),
                ('edition', models.CharField(default=None, max_length=10, null=True)),
                ('series', models.CharField(default=None, max_length=10, null=True)),
                ('volume', models.CharField(default=None, max_length=10, null=True)),
                ('issue', models.CharField(default=None, max_length=10, null=True)),
                ('publisher', models.CharField(default=None, max_length=10, null=True)),
                ('page', models.CharField(default=None, max_length=10, null=True)),
                ('pages', models.CharField(default=None, max_length=10, null=True)),
                ('no_pp', models.CharField(default=None, max_length=10, null=True)),
                ('isbn', models.CharField(default=None, max_length=20, null=True)),
                ('issn', models.CharField(default=None, max_length=20, null=True)),
                ('doi', models.CharField(default=None, max_length=50, null=True)),
                ('url', models.URLField(default=None, null=True)),
                ('access_date', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
    ]
