# Generated by Django 3.2.1 on 2021-10-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20211025_1154'),
    ]

    operations = [
    ]
