# Generated by Django 3.1.6 on 2021-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydjangoapp',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
