# Generated by Django 3.1.6 on 2021-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_auto_20210216_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydjangoapp',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
