# Generated by Django 3.2.1 on 2021-05-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0004_entry_reference_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
