"""
Extracts Railway Company page references from Wikipedia based on pre-specified Wikipedia categories
"""
import requests, csv, os, re
from bs4 import BeautifulSoup
from urllib.request import urlopen

output_file = os.path.join("D:\\Data", "TPAM", "Companies_Extract_Wikipedia.csv")

Categories = ["Early_British_railway_companies",
            "Early_Scottish_railway_companies",
            "Early_Welsh_railway_companies",
            "Pre-grouping_British_railway_companies",
            "Great_Western_Railway_constituents",
            "List_of_constituents_of_the_Great_Western_Railway",
            "London_and_North_Eastern_Railway_constituents",
            "List_of_constituents_of_the_London_and_North_Eastern_Railway",
            "London,_Midland_and_Scottish_Railway_constituents",
            "List_of_constituents_of_the_London,_Midland_and_Scottish_Railway",
            "Southern_Railway_(UK)_constituents",
            "British_joint_railway_companies",
            "Big_four_British_railway_companies",
            "Minor_British_railway_companies",
            "Railway_companies_of_the_United_Kingdom",
            "Predecessor_companies_of_the_London_Underground",
            ]

slug_fullname_exclusions = [
    '/wiki/Infrastructure_of_the_Brill_Tramway',
    '/wiki/Lillie_Bridge_Depot',
    '/wiki/Underground_Electric_Railways_Company_of_London',
    '/wiki/Joint_railway',
    ]

slug_string_exclusions = [
    '/wiki/1948',
    '/wiki/Big_Four_(British_railway_companies)',
    '/wiki/Big_Four_British_railway_companies',
    '/wiki/ISBN_(identifier)',
    '/wiki/Railways_Act_1921',
    '/wiki/Act_of_Parliament',
    '/wiki/Train_operating_company',
    '/wiki/Case_sensitivity',
    ':',
    'List_of',
    "/wiki/British_carriage_and_wagon_numbering_and_classification",
    "/wiki/Railway_Executive_Committee",
    'Main_Page',
    ]

with open(output_file, 'wt+', newline='', encoding='utf-8') as csvFile:
    output = csv.writer(csvFile)
    csvrow = ["category", "wikislug", "name"]
    output.writerow(csvrow)

    for Category in Categories:
        url = f"https://en.wikipedia.org/wiki/Category:{Category}"
        
        try:
            res = requests.get(url).content.decode('utf-8', 'ignore')
        except requests.exceptions.ConnectionError as err:
            # eg, no internet
            raise SystemExit(err) from err
        except requests.exceptions.HTTPError as err:
            # eg, url, server and other errors
            raise SystemExit(err) from err

        soup = BeautifulSoup(res, 'html.parser') 

        for row in soup.find_all(title=True):
            slug = str(row.get('href'))
            if all(x not in slug for x in slug_string_exclusions) \
            and slug not in slug_fullname_exclusions \
            and '/wiki' in slug:
                slug = slug.replace('/wiki/', '')
                csvrow = [Category]
                if slug == "Iarnr%C3%B3d_%C3%89ireann":
                    csvrow.extend(('Iarnród_Éireann', 'Iarnród_Éireann'))
                elif slug in {"North_Eastern_Railway_(United_Kingdom)", "North_Eastern_Railway_(UK)"}:
                    csvrow.extend((slug, 'North Eastern Railway'))
                else:
                    csvrow.extend((slug, row.get('title')))
                output.writerow(csvrow)

    # Companies not in the selected Wikipedia categories as identified by the closed station load
    Additional_Manual_Entries = [
        ["", "Aberford_Railway","Aberford Railway"],
        ["", "Ambergate,_Nottingham,_Boston_and_Eastern_Junction_Railway","Ambergate, Nottingham, Boston and Eastern Junction Railway"],
        ["", "Bala_Lake_Railway","Bala Lake Railway"],
        ["", "Barry_Railway","Barry Railway"],
        ["", "Belfast_and_County_Down_Railway","Belfast and County Down Railway"],
        ["", "Belfast_Central_Railway","Belfast Central Railway"],
        ["", "Bideford,_Westward_Ho!_and_Appledore_Railway","Bideford, Westward Ho! and Appledore Railway"],
        ["", "Birkenhead_Joint_Railway","Birkenhead Joint Railway"],
        ["", "Bishop's_Castle_Railway","Bishop's Castle Railway"],
        ["", "Blackpool_and_Lytham_Railway","Blackpool and Lytham Railway"],
        ["", "Bluebell_Railway","Bluebell Railway"],
        ["", "Blyth_&_Tyne_Railway","Blyth & Tyne Railway"],
        ["", "Blyth_and_Tyne_Railway","Blyth and Tyne Railway"],
        ["", "Brampton_Railway","Brampton Railway"],
        ["", "Brecon_and_Merthyr_Railway","Brecon and Merthyr Railway"],
        ["", "Brighton_and_Dyke_Railway","Brighton and Dyke Railway"],
        ["", "British_Railways","British Railways"],
        ["", "Caledonian_and_Dunbartonshire_Junction_Railway","Caledonian and Dunbartonshire Junction Railway"],
        ["", "Campbeltown_and_Machrihanish_Light_Railway","Campbeltown and Machrihanish Light Railway"],
        ["", "Campbeltown_and_Machrihanish_Railway","Campbeltown and Machrihanish Railway"],
        ["", "Canterbury_and_Whitstable_Railway","Canterbury and Whitstable Railway"],
        ["", "Carlisle_and_Silloth_Bay_Railway","Carlisle and Silloth Bay Railway"],
        ["", "Carnarvon_and_Llanberis_Railway","Carnarvon and Llanberis Railway"],
        ["", "Carnarvonshire_Railway","Carnarvonshire Railway"],
        ["", "Central_London_Railway","Central London Railway"],
        ["", "Charing_Cross,_Euston_and_Hampstead_Railway","Charing Cross, Euston and Hampstead Railway"],
        ["", "Chester_and_Birkenhead_Railway","Chester and Birkenhead Railway"],
        ["", "City_and_South_London_Railway","City and South London Railway"],
        ["", "City_of_Glasgow_Union_Railway","City of Glasgow Union Railway"],
        ["", "Cleator_&_Workington_Junction_Railway","Cleator & Workington Junction Railway"],
        ["", "Cockermouth,_Keswick_&_Penrith_Railway","Cockermouth, Keswick & Penrith Railway"],
        ["", "Cockermouth_&_Workington_Railway","Cockermouth & Workington Railway"],
        ["", "Coleford,_Monmouth,_Usk_and_Pontypool_Railway","Coleford, Monmouth, Usk and Pontypool Railway"],
        ["", "Comrie,_St_Fillans_&_Lochearnhead_Railway","Comrie, St Fillans & Lochearnhead Railway"],
        ["", "Corringham_Light_Railway","Corringham Light Railway"],
        ["", "Deeside_Railway","Deeside Railway"],
        ["", "Denburn_Valley_Line","Denburn Valley Line"],
        ["", "District_Railway","District Railway"],
        ["", "Dundee,_Perth_and_Aberdeen_Junction_Railway","Dundee, Perth and Aberdeen Junction Railway"],
        ["", "Dundee_and_Forfar_Direct_Line","Dundee and Forfar Direct Line"],
        ["", "Easingwold_Railway","Easingwold Railway"],
        ["", "East_and_West_Junction_Railway","East and West Junction Railway"],
        ["", "East_and_West_Yorkshire_Junction_Railway","East and West Yorkshire Junction Railway"],
        ["", "East_Lancashire_Railway_1844-1859","East Lancashire Railway 1844-1859"],
        ["", "East_London_Railway","East London Railway"],
        ["", "East_Norfolk_Railway","East Norfolk Railway"],
        ["", "East_Somerset_Railway","East Somerset Railway"],
        ["", "Edenham_and_Little_Bytham_Railway","Edenham and Little Bytham Railway"],
        ["", "Edinburgh_&_Dalkeith_Railway","Edinburgh & Dalkeith Railway"],
        ["", "Festiniog_and_Blaenau_Railway","Festiniog and Blaenau Railway"],
        ["", "Festiniog_Railway","Festiniog Railway"],
        ["", "Ffestiniog_Railway","Ffestiniog Railway"],
        ["", "Fleetwood,_Preston_and_West_Riding_Junction_Railway","Fleetwood, Preston and West Riding Junction Railway"],
        ["", "Fovant_Military_Railway","Fovant Military Railway"],
        ["", "Foxdale_Railway","Foxdale Railway"],
        ["", "G&SWR","G&SWR"],
        ["", "Glasgow,_Barrhead_and_Neilston_Direct_Railway","Glasgow, Barrhead and Neilston Direct Railway"],
        ["", "Glasgow_&_South_Western_Railway","Glasgow & South Western Railway"],
        ["", "Glasgow_Subway","Glasgow Subway"],
        ["", "Glyn_Valley_Tramway","Glyn Valley Tramway"],
        ["", "GNSR","GNSR"],
        ["", "Golden_Valley_Railway","Golden Valley Railway"],
        ["", "Great_Northern,_Piccadilly_and_Brompton_Railway","Great Northern, Piccadilly and Brompton Railway"],
        ["", "Great_Northern_Railway_(UK)","Great Northern Railway (UK)"],
        ["", "Grimsby_&_Immingham_Electric_Railway","Grimsby & Immingham Electric Railway"],
        ["", "Grimsby_and_Immingham_Electric_Railway","Grimsby and Immingham Electric Railway"],
        ["", "Grimsby_and_Immingham_Tramway","Grimsby and Immingham Tramway"],
        ["", "Halifax_and_Ovenden_Joint_Railway","Halifax and Ovenden Joint Railway"],
        ["", "Halifax_and_Ovenden_Junction_Railway","Halifax and Ovenden Junction Railway"],
        ["", "Halifax_High_Level_Railway","Halifax High Level Railway"],
        ["", "Hammersmith_and_City_Railway","Hammersmith and City Railway"],
        ["", "Hampstead_Junction_Railway","Hampstead Junction Railway"],
        ["", "Hatfield_and_St._Albans_Railway","Hatfield and St. Albans Railway"],
        ["", "Heathrow_Express","Heathrow Express"],
        ["", "Hoylake_Railway","Hoylake Railway"],
        ["", "Hull,_Barnsley_and_West_Riding_Junction_Railway","Hull, Barnsley and West Riding Junction Railway"],
        ["", "Hull_and_Hornsea_Railway","Hull and Hornsea Railway"],
        ["", "Isle_of_Axholme_Joint_Railway","Isle of Axholme Joint Railway"],
        ["", "Isle_of_Man_Railway","Isle of Man Railway"],
        ["", "Isle_of_Wight_(Newport_Junction)_Railway","Isle of Wight (Newport Junction) Railway"],
        ["", "Kent_and_East_Sussex_Light_Railway","Kent and East Sussex Light Railway"],
        ["", "Kilsyth_and_Bonnybridge_Railway","Kilsyth and Bonnybridge Railway"],
        ["", "Knott_End_Railway","Knott End Railway"],
        ["", "L&NWR","L&NWR"],
        ["", "L&SWR","L&SWR"],
        ["", "L&YR","L&YR"],
        ["", "Lanarkshire_and_Dunbartonshire_Railway","Lanarkshire and Dunbartonshire Railway"],
        ["", "Lancashire,_Derbyshire_and_East_Coast_Railway","Lancashire, Derbyshire and East Coast Railway"],
        ["", "Lancashire_&_Yorkshire_Railway","Lancashire & Yorkshire Railway"],
        ["", "Lancashire_Union_Railway","Lancashire Union Railway"],
        ["", "Lancaster_and_Preston_Railway","Lancaster and Preston Railway"],
        ["", "LB&SCR","LB&SCR"],
        ["", "Leeds_Northern_Railway","Leeds Northern Railway"],
        ["", "Lesmahagow_Railway","Lesmahagow Railway"],
        ["", "Lever_Brothers","Lever Brothers"],
        ["", "Liskeard_and_Looe_Railway","Liskeard and Looe Railway"],
        ["", "Little_North_Western_Railway","Little North Western Railway"],
        ["", "Liverpool_&_Manchester_Railway","Liverpool & Manchester Railway"],
        ["", "Llanelly_Railway","Llanelly Railway"],
        ["", "LM&SR","LM&SR"],
        ["", "LNWR","LNWR"],
        ["", "London,_Midland_&_Scottish_Railway","London, Midland & Scottish Railway"],
        ["", "London,_Tilbury_&_Southend_Railway","London, Tilbury & Southend Railway"],
        ["", "London,_Tilbury_and_Southend_Railway","London, Tilbury and Southend Railway"],
        ["", "London_&_Blackwall_Railway","London & Blackwall Railway"],
        ["", "London_&_North_Eastern_Railway","London & North Eastern Railway"],
        ["", "London_&_North_Western_Railway","London & North Western Railway"],
        ["", "London_&_South_Western_Railway","London & South Western Railway"],
        ["", "London_Brighton_and_South_Coast_Railway","London Brighton and South Coast Railway"],
        ["", "London_Midland_and_Scottish_Railway","London Midland and Scottish Railway"],
        ["", "London_Necropolis_Company","London Necropolis Company"],
        ["", "London_Tilbury_and_Southend_Railway","London Tilbury and Southend Railway"],
        ["", "Longmoor_Military_Railway","Longmoor Military Railway"],
        ["", "LSWR","LSWR"],
        ["", "Lynton_&_Barnstaple_Railway","Lynton & Barnstaple Railway"],
        ["", "Lynton_and_Barnstaple_Railway","Lynton and Barnstaple Railway"],
        ["", "M&SWJR","M&SWJR"],
        ["", "Manchester,_Bolton_and_Bury_Canal_Navigation_and_Railway","Manchester, Bolton and Bury Canal Navigation and Railway"],
        ["", "Manchester_Metrolink","Manchester Metrolink"],
        ["", "Manchester_South_Junction_and_Altrincham_Railway","Manchester South Junction and Altrincham Railway"],
        ["", "Maryport_&_Carlisle_Railway","Maryport & Carlisle Railway"],
        ["", "Mersey_Docks_and_Harbour_Board","Mersey Docks and Harbour Board"],
        ["", "Merthyr,_Tredegar_and_Abergavenny_Railway","Merthyr, Tredegar and Abergavenny Railway"],
        ["", "Metropolitan_Railway","Metropolitan Railway"],
        ["", "Mid_Wales_Railway","Mid Wales Railway"],
        ["", "Midland_and_Great_Northern_Railway","Midland and Great Northern Railway"],
        ["", "Military_railway","Military railway"],
        ["", "Monklands_Railway","Monklands Railway"],
        ["", "Muswell_Hill_Railway","Muswell Hill Railway"],
        ["", "Network_Rail","Network Rail"],
        ["", "Newcastle_and_Carlisle_Railway","Newcastle and Carlisle Railway"],
        ["", "Newcastle_and_Darlington_Junction_Railway","Newcastle and Darlington Junction Railway"],
        ["", "Newcastle_and_North_Shields_Railway","Newcastle and North Shields Railway"],
        ["", "Newmarket_Railway","Newmarket Railway"],
        ["", "Newtyle,_Eassie_and_Glamiss_Railway","Newtyle, Eassie and Glamiss Railway"],
        ["", "Nidd_Valley_Light_Railway","Nidd Valley Light Railway"],
        ["", "North_&_South_Western_Junction_Railway","North & South Western Junction Railway"],
        ["", "North_Devon_and_Cornwall_Junction_Light_Railway","North Devon and Cornwall Junction Light Railway"],
        ["", "North_Eastern_Railway_(UK)","North Eastern Railway (UK)"],
        ["", "North_Sunderland_Railway","North Sunderland Railway"],
        ["", "North_Wales_Narrow_Gauge_Railway","North Wales Narrow Gauge Railway"],
        ["", "North_Wales_Narrow_Gauge_Railways","North Wales Narrow Gauge Railways"],
        ["", "Northampton_and_Banbury_Junction_Railway","Northampton and Banbury Junction Railway"],
        ["", "Oldham,_Ashton_and_Guide_Bridge_Junction_Railway","Oldham, Ashton and Guide Bridge Junction Railway"],
        ["", "Pembroke_and_Tenby_Railway","Pembroke and Tenby Railway"],
        ["", "Plynlimon_and_Hafan_Tramway","Plynlimon and Hafan Tramway"],
        ["", "Pontop_and_South_Shields_Railway","Pontop and South Shields Railway"],
        ["", "Port_of_London_Authority","Port of London Authority"],
        ["", "Port_Talbot_Railway","Port Talbot Railway"],
        ["", "Port_Talbot_Railway_and_Docks","Port Talbot Railway and Docks"],
        ["", "Portpatrick_and_Wigtownshire_Railway","Portpatrick and Wigtownshire Railway"],
        ["", "Portpatrick_Railway","Portpatrick Railway"],
        ["", "Potteries,_Shrewsbury_&_North_Wales_Railway","Potteries, Shrewsbury & North Wales Railway"],
        ["", "Potteries,_Shrewsbury_and_North_Wales_Railway","Potteries, Shrewsbury and North Wales Railway"],
        ["", "Preston_and_Wyre_Railway","Preston and Wyre Railway"],
        ["", "Railtrack","Railtrack"],
        ["", "Ravenglass_and_Eskdale_Railway","Ravenglass and Eskdale Railway"],
        ["", "Rhondda_and_Swansea_Bay_Railway","Rhondda and Swansea Bay Railway"],
        ["", "Ringwood,_Christchurch_and_Bournemouth_Railway","Ringwood, Christchurch and Bournemouth Railway"],
        ["", "Romney,_Hythe_&_Dymchurch_Railway","Romney, Hythe & Dymchurch Railway"],
        ["", "Romney,_Hythe_and_Dymchurch_Railway","Romney, Hythe and Dymchurch Railway"],
        ["", "Rye_&_Camber_Tramway","Rye & Camber Tramway"],
        ["", "Rye_and_Camber_Tramway","Rye and Camber Tramway"],
        ["", "Sand_Hutton_Light_Railway","Sand Hutton Light Railway"],
        ["", "Scarborough_&_Whitby_Railway","Scarborough & Whitby Railway"],
        ["", "SE&CR","SE&CR"],
        ["", "Sheffield,_Ashton-Under-Lyne_and_Manchester_Railway","Sheffield, Ashton-Under-Lyne and Manchester Railway"],
        ["", "Sheppey_Light_Railway","Sheppey Light Railway"],
        ["", "Shrewsbury_and_Hereford_Joint_Railway","Shrewsbury and Hereford Joint Railway"],
        ["", "Shrewsbury_and_Welshpool_Railway","Shrewsbury and Welshpool Railway"],
        ["", "Somerset_&_Dorset_Joint_Railway","Somerset & Dorset Joint Railway"],
        ["", "Somerset_and_Dorset_Railway","Somerset and Dorset Railway"],
        ["", "South_Eastern_Railway_(UK)","South Eastern Railway (UK)"],
        ["", "South_Shields,_Marsden_and_Whitburn_Colliery_Railway","South Shields, Marsden and Whitburn Colliery Railway"],
        ["", "South_Staffordshire_Railway","South Staffordshire Railway"],
        ["", "South_Tynedale_Railway","South Tynedale Railway"],
        ["", "South_Yorkshire_Railway","South Yorkshire Railway"],
        ["", "Southern_Railway_(Great_Britain)","Southern Railway (Great Britain)"],
        ["", "Southport_&_Cheshire_Lines_Extension_Railway","Southport & Cheshire Lines Extension Railway"],
        ["", "Southsea_Railway","Southsea Railway"],
        ["", "Southwold_Railway","Southwold Railway"],
        ["", "St._Helens_Railway","St. Helens Railway"],
        ["", "St_Helens_Canal_and_Railway","St Helens Canal and Railway"],
        ["", "St_Helens_Railway","St Helens Railway"],
        ["", "Stirling_&_Dunfermline_Railway","Stirling & Dunfermline Railway"],
        ["", "Stocksbridge_Railway","Stocksbridge Railway"],
        ["", "Stockton_and_Darlington","Stockton and Darlington"],
        ["", "Strathspey_Railway_(preserved)","Strathspey Railway (preserved)"],
        ["", "Swansea_Improvements_and_Tramway_Company","Swansea Improvements and Tramway Company"],
        ["", "Tenbury_&_Bewdley_Railway","Tenbury & Bewdley Railway"],
        ["", "Tenbury_Railway","Tenbury Railway"],
        ["", "Tooting,_Merton_and_Wimbledon_Railway","Tooting, Merton and Wimbledon Railway"],
        ["", "Tottenham_&_Hampstead_Junction_Railway","Tottenham & Hampstead Junction Railway"],
        ["", "Tottenham_and_Hampstead_Junction_Railway","Tottenham and Hampstead Junction Railway"],
        ["", "Vale_of_Rheidol_Railway","Vale of Rheidol Railway"],
        ["", "Vale_of_Towy_Railway","Vale of Towy Railway"],
        ["", "Van_Railway","Van Railway"],
        ["", "Wantage_Tramway","Wantage Tramway"],
        ["", "Warrington_and_Stockport_Railway","Warrington and Stockport Railway"],
        ["", "Welsh_Highland_Railway","Welsh Highland Railway"],
        ["", "West_Cornwall_Railway","West Cornwall Railway"],
        ["", "West_Highland_Railway","West Highland Railway"],
        ["", "West_Lancashire_Railway","West Lancashire Railway"],
        ["", "West_London_Extension_Joint_Railway","West London Extension Joint Railway"],
        ["", "West_Riding_and_Grimsby_Joint_Railway","West Riding and Grimsby Joint Railway"],
        ["", "Weston,_Clevedon_and_Portishead_Railway","Weston, Clevedon and Portishead Railway"],
        ["", "Weymouth_and_Portland_Railway","Weymouth and Portland Railway"],
        ["", "Whitby,_Redcar_and_Middlesbrough_Union_Railway","Whitby, Redcar and Middlesbrough Union Railway"],
        ["", "Whitby_Redcar_and_Middlesbrough_Union_Railway","Whitby Redcar and Middlesbrough Union Railway"],
        ["", "Whitehaven,_Cleator_and_Egremont_Junction_Railway","Whitehaven, Cleator and Egremont Junction Railway"],
        ["", "Whitehaven,_Cleator_and_Egremont_Railway","Whitehaven, Cleator and Egremont Railway"],
        ["", "Whitehaven_and_Furness_Junction_Railway","Whitehaven and Furness Junction Railway"],
        ["", "Wick_and_Lybster_Railway","Wick and Lybster Railway"],
        ["", "Wigan_Junction_Railways","Wigan Junction Railways"],
        ["", "Wilsontown,_Morningside_and_Coltness_Railway","Wilsontown, Morningside and Coltness Railway"],
        ["", "Woodside_and_South_Croydon_Railway","Woodside and South Croydon Railway"],
        ["", "Wrexham_and_Minera_Branch","Wrexham and Minera Branch"],
        ["", "York,_Newcastle_and_Berwick_Railway","York, Newcastle and Berwick Railway"],
        ]

    for entry in Additional_Manual_Entries:
        output.writerow(entry)