# Generated by Django 3.1.6 on 2021-02-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPAM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depots',
        ),
        migrations.DeleteModel(
            name='LocomotiveClass',
        ),
        migrations.DeleteModel(
            name='Locomotive',
        ),
        migrations.DeleteModel(
            name='Manufacturers',
        ),
        migrations.DeleteModel(
            name='WheelArrangement',
        ),
        migrations.DeleteModel(
            name='LocosEngineer',
        ),
        migrations.DeleteModel(
            name='LocosEntry',
        ),
        migrations.DeleteModel(
            name='LocosLocomotiveclass',
        ),
        migrations.DeleteModel(
            name='LocosTopic',
        ),
    ]
