# Generated by Django 3.2.1 on 2023-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_post_references'),
        ('locos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lococlass',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
    ]
