# Generated by Django 3.2.1 on 2022-01-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='graceslug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
