# Generated by Django 3.2.1 on 2024-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lococlass',
            name='slug',
            field=models.CharField(blank=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated from name.', max_length=255, null=True, unique=True),
        ),
    ]
