# Generated by Django 3.2.1 on 2021-10-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0002_auto_20211025_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.role')),
            ],
        ),
    ]
