# Generated by Django 3.2.1 on 2022-11-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0002_elr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ELR',
        ),
    ]
