# Generated by Django 3.2.1 on 2024-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0002_alter_lococlass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lococlass',
            name='slug',
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
