# Generated by Django 3.2.1 on 2023-06-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_auto_20230620_0909"),
        ("companies", "0002_company_company_category_fk"),
        ("notes", "0013_rename_citation_reference_full_reference"),
        ("locos", "0002_auto_20230329_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="lococlass",
            name="designer_company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="lococlass",
            name="designer_person",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="lococlass",
            name="manufacturers",
            field=models.ManyToManyField(
                blank=True,
                related_name="lococlass_manufacturers",
                to="companies.Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="lococlass",
            name="owner_operators",
            field=models.ManyToManyField(
                blank=True,
                related_name="lococlass_owner_operators",
                to="companies.Company",
            ),
        ),
        migrations.AlterField(
            model_name="lococlass",
            name="references",
            field=models.ManyToManyField(
                blank=True, related_name="lococlass_references", to="notes.Reference"
            ),
        ),
    ]
