# Generated by Django 3.2.1 on 2022-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0002_auto_20220102_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='manufacturer_code',
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='brd_manufacturer_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='railuk_manufacturer_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='wikislug',
            field=models.SlugField(default=None),
        ),
    ]
