# Generated by Django 3.2.1 on 2022-01-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0003_auto_20220103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
