# Generated by Django 3.2.1 on 2022-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0004_locomotive_number_as_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotive',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
