# Generated by Django 3.2.1 on 2022-11-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20220503_1606'),
        ('locations', '0011_locationevent_elr_fk'),
        ('locos', '0005_alter_locomotive_order_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sighting',
            new_name='Reference',
        ),
    ]
