# Generated by Django 3.2.1 on 2022-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0005_alter_manufacturers_wikislug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='brsl_manufacturer_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
