# Generated by Django 3.2.1 on 2022-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0007_alter_manufacturers_brsl_manufacturer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wikislug', models.SlugField(default=None, max_length=200)),
                ('railuk_company_code', models.CharField(blank=True, max_length=6, null=True)),
                ('brd_company_code', models.CharField(blank=True, max_length=6, null=True)),
                ('brsl_company_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
