# Generated by Django 3.2.1 on 2022-11-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20221128_1510'),
        ('locos', '0007_auto_20221123_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='routemap_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.routemap'),
        ),
    ]
