# Generated by Django 3.2.1 on 2023-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0008_reference_routemap_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='locos',
        ),
        migrations.AddField(
            model_name='reference',
            name='date_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='loco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
