# Generated by Django 3.2.1 on 2023-01-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0009_auto_20230111_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lococlass',
            options={'managed': True, 'verbose_name': 'Locomotive Class', 'verbose_name_plural': 'Locomotive Classes'},
        ),
        migrations.AlterModelOptions(
            name='lococlasslist',
            options={'verbose_name': 'Locomotive Class Mapping', 'verbose_name_plural': 'Locomotive Class Mappings'},
        ),
        migrations.AlterModelOptions(
            name='lococlasssighting',
            options={'verbose_name': 'Locomotive Class Sighting', 'verbose_name_plural': 'Locomotive Class Sightings'},
        ),
    ]
