# Generated by Django 3.2.1 on 2022-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0009_category_companycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='br_region_owner',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='grouping_owner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='pre_grouping_owner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
