# Generated by Django 3.2.1 on 2022-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0010_auto_20220105_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='brd_company_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='brsl_company_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='railuk_company_code',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='grouping_owner',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='pre_grouping_owner',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
