# Generated by Django 3.2.1 on 2023-01-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0010_auto_20230124_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='type',
        ),
    ]
