# Generated by Django 3.2.1 on 2022-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0011_auto_20220105_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
