# Generated by Django 3.2.1 on 2023-01-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0011_remove_reference_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='ELR_fk',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='company_fk',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='date_datetime',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='location_fk',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='lococlass',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='route_fk',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='routemap_fk',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='visit',
        ),
    ]
