# Generated by Django 3.2.1 on 2022-01-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0013_lococlass_adhesive_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lococlass',
            name='axle_load',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
