# Generated by Django 3.2.1 on 2023-01-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0014_auto_20230124_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='location_fk',
        ),
    ]
