# Generated by Django 3.2.1 on 2023-01-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_auto_20230124_1104'),
        ('locos', '0015_auto_20230124_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='location_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
