# Generated by Django 3.2.1 on 2023-01-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_post_body'),
        ('locos', '0017_auto_20230124_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locomotive',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.AddField(
            model_name='builder',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
        migrations.AddField(
            model_name='company',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
        migrations.AddField(
            model_name='lococlass',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
        migrations.AddField(
            model_name='person',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
    ]
