# Generated by Django 3.2.1 on 2022-01-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0018_auto_20220109_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wikislug', models.SlugField(default=None, max_length=200)),
                ('railuk_builder_code', models.CharField(blank=True, max_length=3, null=True)),
                ('brd_builder_code', models.CharField(blank=True, max_length=3, null=True)),
                ('brsl_builder_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pre_grouping_owner', models.CharField(blank=True, default='', max_length=10)),
                ('grouping_owner', models.CharField(blank=True, default='', max_length=4)),
                ('br_region_owner', models.CharField(blank=True, default='', max_length=3)),
                ('date_opened', models.CharField(blank=True, max_length=10, null=True)),
                ('date_closed', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=77, null=True)),
                ('steam', models.CharField(blank=True, max_length=10, null=True)),
                ('diesel', models.CharField(blank=True, max_length=10, null=True)),
                ('electric', models.CharField(blank=True, max_length=10, null=True)),
                ('map', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Builder',
            },
        ),
        migrations.CreateModel(
            name='ClassBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.builder')),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.company')),
                ('lococlass_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.lococlass')),
                ('person_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Manufacturers',
        ),
        migrations.RenameField(
            model_name='locomotive',
            old_name='manufacturer',
            new_name='builder',
        ),
        migrations.RenameField(
            model_name='modernclass',
            old_name='manufacturer',
            new_name='builder',
        ),
    ]
