# Generated by Django 3.2.1 on 2022-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0021_auto_20220112_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='born',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='died',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
