# Generated by Django 3.2.1 on 2022-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0022_auto_20220113_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='died',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
