# Generated by Django 3.2.1 on 2022-01-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0024_auto_20220113_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lococlass',
            name='adhesion_factor',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='cylinders',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='firegrate_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='gauge',
            field=models.CharField(blank=True, default='', max_length=175),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='tender_weight',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='water_capacity',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
