# Generated by Django 3.2.1 on 2022-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0025_auto_20220113_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='graceslug',
            field=models.SlugField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='wikislug',
            field=models.SlugField(blank=True, default=None),
        ),
    ]
