# Generated by Django 3.2.1 on 2022-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0027_remove_person_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='graceslug',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wikislug',
        ),
        migrations.AddField(
            model_name='person',
            name='gracetextslug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='wikiimageslug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='wikiimagetext',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='wikitextslug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
