# Generated by Django 3.2.1 on 2022-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0028_auto_20220115_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
