# Generated by Django 3.2.1 on 2022-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0030_remove_sighting_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='born',
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
