# Generated by Django 3.2.1 on 2022-01-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0032_auto_20220118_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOwnerOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.company')),
                ('lococlass_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.lococlass')),
            ],
        ),
    ]
