# Generated by Django 3.2.1 on 2022-01-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0035_auto_20220121_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
