# Generated by Django 3.2.1 on 2022-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0036_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lococlass',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='lococlass',
            name='designer_slug',
        ),
        migrations.AddField(
            model_name='builder',
            name='lococlass_designed',
            field=models.ManyToManyField(related_name='builder_designer', through='locos.ClassDesigner', to='locos.LocoClass'),
        ),
        migrations.AddField(
            model_name='company',
            name='lococlass_designed',
            field=models.ManyToManyField(related_name='company_designer', through='locos.ClassDesigner', to='locos.LocoClass'),
        ),
        migrations.AddField(
            model_name='person',
            name='lococlass_designed',
            field=models.ManyToManyField(related_name='engineer_designer', through='locos.ClassDesigner', to='locos.LocoClass'),
        ),
    ]
