# Generated by Django 3.2.1 on 2022-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0038_alter_person_lococlass_designed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='lococlass_designed',
            field=models.ManyToManyField(through='locos.ClassDesigner', to='locos.LocoClass'),
        ),
    ]
