# Generated by Django 3.2.1 on 2022-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0039_alter_builder_lococlass_designed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='builder_name',
            new_name='name',
        ),
    ]
