# Generated by Django 3.2.1 on 2022-02-27 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0045_alter_sighting_hyperlink'),
    ]

    operations = [

    ]
