# Generated by Django 3.2.1 on 2022-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0046_locations'),
    ]

    operations = [

    ]
