# Generated by Django 3.2.1 on 2022-02-27 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0047_delete_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('wikiname', models.CharField(blank=True, max_length=200, null=True)),
                ('wikislug', models.SlugField(default=None, max_length=255, null=True)),
                ('disusedslug', models.SlugField(default=None, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('closed', models.CharField(blank=True, max_length=50, null=True)),
                ('disused_stations_slug', models.CharField(blank=True, max_length=200, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('atcocode', models.CharField(blank=True, max_length=20, null=True)),
                ('tiploccode', models.CharField(blank=True, max_length=20, null=True)),
                ('crscode', models.CharField(blank=True, max_length=10, null=True)),
                ('stationname', models.CharField(blank=True, max_length=100, null=True)),
                ('stationnamelang', models.CharField(blank=True, max_length=2, null=True)),
                ('gridtype', models.CharField(blank=True, max_length=1, null=True)),
                ('easting', models.PositiveIntegerField(blank=True, null=True)),
                ('northing', models.PositiveIntegerField(blank=True, null=True)),
                ('revisionnumber', models.SmallIntegerField(blank=True, null=True)),
                ('modification', models.CharField(blank=True, max_length=3, null=True)),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.company')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
