# Generated by Django 3.2.1 on 2022-02-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0048_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='closed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
