# Generated by Django 3.2.1 on 2022-02-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0049_alter_locations_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='location',
        ),
        migrations.DeleteModel(
            name='HeritageSite',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
