# Generated by Django 3.2.1 on 2022-05-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0050_auto_20220228_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='loco_class',
        ),
        migrations.CreateModel(
            name='LocoClassImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.image')),
                ('loco_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.lococlass')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='lococlass',
            field=models.ManyToManyField(through='locos.LocoClassImage', to='locos.LocoClass'),
        ),
    ]
