# Generated by Django 3.2.1 on 2022-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0051_auto_20220504_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lococlasssighting',
            old_name='sighting',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='locosighting',
            old_name='sighting',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='citation_specifics',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='hyperlink',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='orientation',
        ),
        migrations.AddField(
            model_name='sighting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Book'), (2, 'Website'), (3, 'Magazine'), (4, 'Video'), (5, 'Sighting')], default=1),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='citation',
            field=models.TextField(blank='True', default=None, null='True'),
        ),
    ]
