# Generated by Django 3.2.1 on 2022-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0053_auto_20220505_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
