# Generated by Django 3.2.1 on 2022-05-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0054_locomotive_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeritageLocoSeen',
            new_name='LocoImage',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='loco_classes',
            new_name='lococlass',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='modern_class',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='steam_class',
        ),
        migrations.AddField(
            model_name='locomotive',
            name='lococlass',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='locos.lococlass', verbose_name='Locomotive Class'),
        ),
        migrations.DeleteModel(
            name='ModernClass',
        ),
    ]
