# Generated by Django 3.2.1 on 2022-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0056_auto_20220506_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lococlass',
            name='tractive_effort',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
