# Generated by Django 3.2.1 on 2022-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0057_alter_lococlass_tractive_effort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lococlass',
        ),
        migrations.RemoveField(
            model_name='lococlass',
            name='wikipedia_slug',
        ),
        migrations.AddField(
            model_name='company',
            name='lococlass_owneroperator',
            field=models.ManyToManyField(related_name='company_owneroperator', through='locos.ClassOwnerOperator', to='locos.LocoClass'),
        ),
    ]
