# Generated by Django 3.2.1 on 2022-05-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0059_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='company_fk',
        ),
        migrations.AddField(
            model_name='route',
            name='locations',
            field=models.ManyToManyField(to='locos.Locations'),
        ),
        migrations.CreateModel(
            name='RouteOwnerOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.company')),
                ('route_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.route')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='route_owneroperator',
            field=models.ManyToManyField(related_name='route_owneroperator', through='locos.RouteOwnerOperator', to='locos.Route'),
        ),
    ]
