# Generated by Django 3.2.1 on 2022-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0060_auto_20220518_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='wikicategory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
