# Generated by Django 3.2.1 on 2022-05-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0062_auto_20220519_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='wikicategory',
        ),
        migrations.AddField(
            model_name='route',
            name='template_wikislug',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RouteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.CharField(blank=True, max_length=200, null=True)),
                ('td1', models.CharField(blank=True, max_length=200, null=True)),
                ('td2', models.CharField(blank=True, max_length=200, null=True)),
                ('td3', models.CharField(blank=True, max_length=200, null=True)),
                ('td4', models.CharField(blank=True, max_length=200, null=True)),
                ('td5', models.CharField(blank=True, max_length=200, null=True)),
                ('td6', models.CharField(blank=True, max_length=200, null=True)),
                ('route_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locos.route')),
            ],
        ),
    ]
