# Generated by Django 3.2.1 on 2022-05-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0063_auto_20220531_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_categories',
        ),
        migrations.RemoveField(
            model_name='route',
            name='template_wikislug',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='route_fk',
        ),
        migrations.AddField(
            model_name='route',
            name='wikipedia_route_categories',
            field=models.ManyToManyField(to='locos.RouteCategory'),
        ),
        migrations.AddField(
            model_name='route',
            name='wikipedia_routemaps',
            field=models.ManyToManyField(to='locos.RouteMap'),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='routemap_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locos.routemap'),
        ),
    ]
