# Generated by Django 3.2.1 on 2022-05-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0064_auto_20220531_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='wikislug',
            new_name='wikipedia_slug',
        ),
    ]
