# Generated by Django 3.2.1 on 2022-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0065_rename_wikislug_route_wikipedia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemap',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
