# Generated by Django 3.2.1 on 2022-06-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0068_auto_20220531_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routelocation',
            name='td1',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='td2',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='td3',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='td4',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='td5',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='td6',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='tr',
        ),
        migrations.AddField(
            model_name='routelocation',
            name='icons',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='loc_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routelocation',
            name='location_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.locations'),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
