# Generated by Django 3.2.1 on 2022-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0069_auto_20220610_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routelocation',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='name',
        ),
        migrations.AddField(
            model_name='routelocation',
            name='item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
