# Generated by Django 3.2.1 on 2022-07-05 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0070_auto_20220616_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocosRoutesGeoClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
            ],
            options={
                'db_table': 'locos_routes_geo_closed',
                'managed': True,
            },
        ),
    ]
