# Generated by Django 3.2.1 on 2022-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0073_auto_20220705_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locosroutesgeoclosed',
            name='name',
            field=models.TextField(blank=True, db_column='name', null=True),
        ),
    ]
