# Generated by Django 3.2.1 on 2022-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0074_alter_locosroutesgeoclosed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='opened',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
