# Generated by Django 3.2.1 on 2022-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0076_locations_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='disusedslug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='wikislug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
