# Generated by Django 3.2.1 on 2022-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0077_auto_20220711_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='routelocation',
            name='label_html',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
