# Generated by Django 3.2.1 on 2022-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0078_routelocation_label_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routelocation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='label_html',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='type',
        ),
        migrations.AddField(
            model_name='routelocation',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
