# Generated by Django 3.2.1 on 2022-07-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0079_auto_20220714_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='DD',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='HH',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='MM',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='SS',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='YD',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='YY',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='easting',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='northing',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='short_description',
        ),
        migrations.AddField(
            model_name='sighting',
            name='date',
            field=models.CharField(blank='True', default='??/??/?? ??:??:??', max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='sighting',
            name='location_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.locations'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='citation',
            field=models.TextField(blank='True', default='cite book                 | last1 =  | first1 =                 | title = [[ ]]                 | location =                   | publisher = [[]]                 | pages = 1-2                 | date = ??/??/??                 | isbn = 0-786918-50-0                 | journal =                  | volume = 19                 | issue = 1                 | issn =', null='True'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Book'), (2, 'Website'), (3, 'Magazine'), (4, 'Video'), (5, 'MySighting'), (6, 'MyPhoto')], default=1),
        ),
    ]
