# Generated by Django 3.2.1 on 2022-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0080_auto_20220723_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='locations',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='citation',
            field=models.TextField(blank='True', default='cite book | last1 = | first1 = | title = [[ ]] | publisher = [[]] | pages = 1-2  | date = ??/??/?? | isbn = 0-786918-50-0 | journal = | volume = | issue = | issn = ', null='True'),
        ),
    ]
