# Generated by Django 3.2.1 on 2022-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0081_auto_20220724_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='lococlasslist',
            name='brdslug',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='img_slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lococlass',
            name='number_range_slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
