# Generated by Django 3.2.1 on 2022-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0082_auto_20220811_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locomotive',
            old_name='build_date',
            new_name='brd_build_date',
        ),
        migrations.RenameField(
            model_name='locomotive',
            old_name='builder',
            new_name='brd_builder',
        ),
        migrations.RenameField(
            model_name='locomotive',
            old_name='number',
            new_name='brd_number_as_built',
        ),
        migrations.RenameField(
            model_name='locomotive',
            old_name='order_number',
            new_name='brd_order_number',
        ),
        migrations.RenameField(
            model_name='locomotive',
            old_name='works_number',
            new_name='brd_works_number',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='wheel_arrangement',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='wikipedia_name',
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='withdrawn',
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_class_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_class_name_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_order_number_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_withdrawn_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lococlasslist',
            name='brdslug',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lococlasslist',
            name='wikislug',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
