# Generated by Django 3.2.1 on 2022-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0083_auto_20220811_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='brd_company_grouping_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_company_pregrouping_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
