# Generated by Django 3.2.1 on 2022-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0084_auto_20220812_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='ref',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
