# Generated by Django 3.2.1 on 2022-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0085_sighting_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locomotive',
            old_name='brd_build_date',
            new_name='brd_build_date_recorded',
        ),
        migrations.AddField(
            model_name='locomotive',
            name='brd_build_date_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
