# Generated by Django 3.2.1 on 2022-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0087_auto_20220815_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='locomotive',
            name='identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
