# Generated by Django 3.2.1 on 2022-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0088_locomotive_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lococlass',
            name='brdslug',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
