# Generated by Django 3.2.1 on 2022-09-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0089_lococlass_brdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lococlasssighting',
            name='loco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.locomotive'),
        ),
        migrations.AlterField(
            model_name='lococlasssighting',
            name='loco_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.lococlass'),
        ),
    ]
