# Generated by Django 3.2.1 on 2022-09-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0090_auto_20220915_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lococlassimage',
            name='loco_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locos.lococlass'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='locos',
            field=models.ManyToManyField(through='locos.LocoClassSighting', to='locos.Locomotive'),
        ),
        migrations.DeleteModel(
            name='LocoSighting',
        ),
    ]
