# Generated by Django 3.2.1 on 2022-09-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locos', '0091_auto_20220915_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routelocation',
            old_name='routemap_fk',
            new_name='routemap',
        ),
    ]
