# Generated by Django 3.2.1 on 2023-05-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naptanrailreferences',
            old_name='stationname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='naptanrailreferences',
            old_name='stationnamelang',
            new_name='namelang',
        ),
    ]
