from django.db import models
from .models import *
from notes.models import Post, Reference

import sys

sys.path.append("..")
from utils.utils import custom_slugify


class Role(models.Model):
    role = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.role

    class Meta:
        managed = True


class Person(models.Model):
    SOURCE_TYPE = (
        (1, "Wikipedia"),
        (2, "Custom"),
        (3, "South Western Railway Magazine"),
    )
    name = models.CharField(max_length=100, blank=True, default="")
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        max_length=255,
        unique=True,
        help_text="Enter a slug only if you wish to override that which will be autogenerated from name.",
    )
    firstname = models.CharField(max_length=100, default=None)
    surname = models.CharField(max_length=100, default=None)
    title = models.CharField(max_length=100, blank=True, null=True, default=None)
    birthdate = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )
    birthplace = models.CharField(max_length=200, blank=True, default="")
    dieddate = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )
    diedplace = models.CharField(max_length=200, blank=True, default="")
    nationality = models.CharField(max_length=200, blank=True, default="")
    occupation = models.CharField(max_length=200, blank=True, default="")
    wikitextslug = models.CharField(max_length=200, blank=True, default="")
    wikiimageslug = models.CharField(max_length=200, blank=True, default="")
    wikiimagetext = models.CharField(max_length=200, blank=True, default="")
    gracetextslug = models.CharField(max_length=200, blank=True, default="")
    roles = models.ManyToManyField(
        Role, through="PersonRole", related_name="persons", blank=True
    )
    post_fk = models.ForeignKey(
        Post, on_delete=models.SET_NULL, blank=True, null=True, default=None
    )
    references = models.ManyToManyField(Reference, blank=True)
    source = models.IntegerField(
        choices=SOURCE_TYPE,
        default=1,
    )
    date_added = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("people:person", kwargs={"person_id": self.pk})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.name).replace("-", "_")
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "People"
        ordering = ("name",)


class PersonRole(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    date_from = models.CharField(max_length=10, blank=True, default="")
    date_to = models.CharField(max_length=10, blank=True, default="")

    def __str__(self):
        return f"{self.person} {self.role}"

    class Meta:
        verbose_name = "Person Role"
        verbose_name_plural = "People Role"
