from django.db import models

import sys

sys.path.append("..")
from utils.utils import custom_slugify


class TimelineSlideHeader(models.Model):
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        max_length=255,
        unique=True,
        help_text="Enter a slug only if you wish to override that which will be autogenerated from the text headline.",
    )
    # location_line = models.BooleanField(default=True)
    media_caption = models.CharField(max_length=100, blank=True, default="")
    media_credit = models.CharField(max_length=200, blank=True, default="")
    media_url = models.URLField(blank=True, default="", max_length=300)
    text_headline = models.CharField(max_length=200, blank=True, null=True)
    text_text = models.TextField(blank=True, null=True)
    type = models.CharField(default="overview", max_length=20)
    wikipedia_name = models.CharField(max_length=1000, blank=True, default="")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.text_headline).replace("-", "_")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.text_headline


class TimelineSlide(models.Model):
    slideheader = models.ManyToManyField(
        TimelineSlideHeader, through="TimelineSlidepack", related_name="slidepack_slide"
    )
    media_caption = models.CharField(max_length=100, blank=True, default="")
    media_credit = models.CharField(max_length=200, blank=True, default="")
    media_url = models.URLField(blank=True, max_length=400, default="")
    text_headline = models.CharField(max_length=200, blank=True, null=True)
    text_text = models.TextField(blank=True, null=True)
    wikipedia_name = models.CharField(max_length=1000, blank=True, default="")
    start_date = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )
    end_date = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Format YYYY-MM-DD with only YY mandatory; Leading zeros on mmy and yy; Can use ? for any unknown digit",
    )

    def __str__(self):
        return self.text_headline


class TimelineSlidepack(models.Model):
    slideheader_fk = models.ForeignKey(TimelineSlideHeader, on_delete=models.CASCADE)
    slide_fk = models.ForeignKey(TimelineSlide, on_delete=models.CASCADE)
    slide_order = models.SmallIntegerField()

    def __str__(self):
        return (
            f"{self.slideheader_fk} TimelineSlide {self.slide_order} : {self.slide_fk}"
        )
