# Generated by Django 3.2.1 on 2022-01-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airclass', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('wikislug', models.SlugField(blank=True, default=None, max_length=250, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Aircraft Classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AirImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('airclass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftclass', verbose_name='Aircraft Class')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.heritagesite', verbose_name='Location')),
                ('visit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.visit', verbose_name='Visit')),
            ],
        ),
        migrations.CreateModel(
            name='AirBMImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airimages_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='airimages_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
