# Generated by Django 3.2.1 on 2021-05-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_heritagesite_visit'),
        ('aircraft', '0002_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='location',
        ),
        migrations.AlterField(
            model_name='airimage',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.heritagesite', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='airimage',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='maps.visit', verbose_name='Visit'),
        ),
        migrations.DeleteModel(
            name='HeritageSite',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
