# Generated by Django 3.2.1 on 2023-03-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Book'), (2, 'Website'), (
                    3, 'Magazine'), (4, 'Video'), (5, 'MySighting'), (6, 'MyPhoto')])),
                ('citation', models.TextField(
                    blank='True', default='cite book | last1 = | first1 = | title = [[ ]] | publisher = [[]] | pages = 1-2  | date = ??/??/?? | isbn = 0-786918-50-0 | journal = | volume = | issue = | issn = ', null='True')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField(blank='True', default=None, null='True')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('date_datetime', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, verbose_name='Topic Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                 to='mainmenu.mydjangoapp', verbose_name='Topic Type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(blank=True,
                 default=None, max_length=255, null=True)),
                ('body', models.TextField(default=None)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[
                 ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('liked', models.ManyToManyField(
                    blank=True, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='post_owner', to=settings.AUTH_USER_MODEL)),
                ('references', models.ManyToManyField(to='notes.Reference')),
                ('topic', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='notes.topic')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
    ]
