# Generated by Django 3.2.1 on 2024-02-06 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRMPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivenumber', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('scale', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tube', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('roll', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('drawingno', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('negativeno', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('material', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bluebell Railway Archive Maps & Plans',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Book'), (2, 'Website'), (3, 'Journal, Periodical or Magazine'), (4, 'Video'), (5, 'MySighting'), (6, 'MyPhoto')])),
                ('full_reference', models.CharField(blank='True', default=None, max_length=300, null='True')),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, null=True)),
                ('day', models.IntegerField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('authors', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('editors', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('journal', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('chapter', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('volume', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('issue', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pages', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('publisher', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_issn', message='Invalid ISSN number. It should be in the format XXXX-XXX(X).', regex='^\\d{4}-\\d{3}[\\dX]$')])),
                ('issn', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('doi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, verbose_name='Topic Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainmenu.mydjangoapp', verbose_name='Topic Type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(blank=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated from the Post Title.', max_length=255, null=True, unique=True)),
                ('body', models.TextField(default=None)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
                ('references', models.ManyToManyField(blank=True, to='notes.Reference')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.topic')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
    ]
