# Generated by Django 3.2.1 on 2023-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
    ]
