# Generated by Django 3.2.1 on 2023-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_post_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='citation',
            field=models.CharField(blank='True', default='cite book | last1 = | first1 = | title = [[ ]] | publisher = [[]] | pages = 1-2  | date = ??/??/?? | isbn = 0-786918-50-0 | journal = | volume = | issue = | issn = ', max_length=1000, null='True'),
        ),
    ]
