# Generated by Django 3.2.1 on 2023-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_reference_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='notes',
        ),
        migrations.AlterField(
            model_name='reference',
            name='citation',
            field=models.TextField(blank='True', default='cite book | last1 = | first1 = | title = [[ ]] | publisher = [[]] | pages = 1-2  | date = ??/??/?? | isbn = 0-786918-50-0 | journal = | volume = | issue = | issn = ', null='True'),
        ),
    ]
