# Generated by Django 3.2.1 on 2023-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20230614_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='date_datetime',
        ),
        migrations.AddField(
            model_name='reference',
            name='access_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='chapter',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='citation_auto',
            field=models.CharField(blank='True', max_length=300, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='reference',
            name='day',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='edition',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='editors',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='isbn',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='issn',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='issue',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='month',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='pages',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='publisher',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='volume',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='type',
            field=models.IntegerField(choices=[(1, 'Book'), (2, 'Website'), (3, 'Journal, Periodical or Magazine'), (4, 'Video'), (5, 'MySighting'), (6, 'MyPhoto')]),
        ),
    ]
