# Generated by Django 3.2.1 on 2023-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20230617_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='day',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
