# Generated by Django 3.2.1 on 2023-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20230617_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='issue',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
