# Generated by Django 3.2.1 on 2023-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_reference_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='citation_auto',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ref',
        ),
        migrations.AlterField(
            model_name='reference',
            name='citation',
            field=models.CharField(blank='True', default=None, max_length=300, null='True'),
        ),
    ]
