# Generated by Django 3.2.1 on 2023-06-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20230617_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='date',
        ),
    ]
