# Generated by Django 3.2.1 on 2023-06-17 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_remove_reference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=None, help_text='Enter the slug for the URL. Uses underscore (_) as a separator.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_issn', message='Invalid ISSN number. It should be in the format XXXX-XXX(X).', regex='^\\d{4}-\\d{3}[\\dX]$')]),
        ),
    ]
