# Generated by Django 3.2.1 on 2023-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20230617_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
