# Generated by Django 3.2.1 on 2023-06-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_reference_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='citation',
            new_name='full_reference',
        ),
    ]
