# Generated by Django 3.2.1 on 2024-02-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('wikislug', models.SlugField(allow_unicode=True, blank=True, default=None, max_length=250, null=True)),
                ('railuk_manufacturer_code', models.CharField(blank=True, max_length=3, null=True)),
                ('brd_manufacturer_code', models.CharField(blank=True, max_length=3, null=True)),
                ('brsl_manufacturer_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pre_grouping_owner', models.CharField(blank=True, default='', max_length=10)),
                ('grouping_owner', models.CharField(blank=True, default='', max_length=4)),
                ('br_region_owner', models.CharField(blank=True, default='', max_length=3)),
                ('date_opened', models.CharField(blank=True, max_length=10, null=True)),
                ('date_closed', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=77, null=True)),
                ('steam', models.CharField(blank=True, max_length=10, null=True)),
                ('diesel', models.CharField(blank=True, max_length=10, null=True)),
                ('electric', models.CharField(blank=True, max_length=10, null=True)),
                ('map', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.CharField(blank=True, max_length=200, null=True)),
                ('post_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.post')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('wikislug', models.SlugField(allow_unicode=True, blank=True, default=None, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_formed', models.CharField(blank=True, max_length=200, null=True)),
                ('date_succeeded', models.CharField(blank=True, max_length=200, null=True)),
                ('company_category_fk', models.ManyToManyField(blank=True, to='companies.CompanyCategory')),
                ('post_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.post')),
                ('successor_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
