# Generated by Django 3.2.1 on 2023-03-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_category_fk",
            field=models.ManyToManyField(blank=True, to="companies.CompanyCategory"),
        ),
    ]
