# Generated by Django 3.2.1 on 2023-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_category_fk',
        ),
        migrations.AddField(
            model_name='company',
            name='company_category_fk',
            field=models.ManyToManyField(blank=True, to='companies.CompanyCategory'),
        ),
    ]
