# Generated by Django 3.2.1 on 2024-02-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_successor_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='brd_manufacturer_code',
            new_name='brd_code',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='brsl_manufacturer_code',
            new_name='brsl_code',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='railuk_manufacturer_code',
            new_name='railuk_code',
        ),
    ]
