# Generated by Django 3.2.1 on 2024-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20240208_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='wikislug',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
