# Generated by Django 3.2.1 on 2024-02-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated from name.', max_length=255, null=True, unique=True)),
                ('firstname', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('birthdate', models.CharField(blank=True, default='', max_length=10)),
                ('birthplace', models.CharField(blank=True, default='', max_length=200)),
                ('dieddate', models.CharField(blank=True, default='', max_length=10)),
                ('diedplace', models.CharField(blank=True, default='', max_length=200)),
                ('nationality', models.CharField(blank=True, default='', max_length=200)),
                ('occupation', models.CharField(blank=True, default='', max_length=200)),
                ('wikitextslug', models.CharField(blank=True, default='', max_length=200)),
                ('wikiimageslug', models.CharField(blank=True, default='', max_length=200)),
                ('wikiimagetext', models.CharField(blank=True, default='', max_length=200)),
                ('gracetextslug', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.IntegerField(choices=[(1, 'Wikipedia'), (2, 'Custom'), (3, 'South Western Railway Magazine')], default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.post')),
                ('references', models.ManyToManyField(blank=True, to='notes.Reference')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(blank=True, default='', max_length=10)),
                ('date_to', models.CharField(blank=True, default='', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.role')),
            ],
            options={
                'verbose_name': 'Person Role',
                'verbose_name_plural': 'People Role',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, through='people.PersonRole', to='people.Role'),
        ),
    ]
