# Generated by Django 3.2.1 on 2023-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.IntegerField(choices=[(1, 'Wikipedia'), (2, 'Custom')], default=1),
        ),
    ]
