# Generated by Django 3.2.1 on 2024-02-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='persons', through='people.PersonRole', to='people.Role'),
        ),
    ]
