# Generated by Django 3.2.1 on 2023-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ManyToManyField(blank=True, to='people.Role'),
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
    ]
