# Generated by Django 3.2.1 on 2023-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_post_references'),
        ('people', '0004_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
    ]
