# Generated by Django 3.2.1 on 2023-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_auto_20230620_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(default=None, max_length=100, blank=True, null=True),
        ),
    ]
