# Generated by Django 3.2.1 on 2021-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uklicensedvehicles',
            name='year_licensed',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
