# Generated by Django 3.2.1 on 2021-10-25 10:54

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_uklicensedvehicles_year_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uklicensedvehicles',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='make', chained_model_field='make', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='uklicensedvehicles',
            name='variant',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='model', chained_model_field='model', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclevariant'),
        ),
    ]
