# Generated by Django 3.2.1 on 2024-02-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.URLField(blank=True, max_length=300, null=True)),
                ('northing', models.FloatField(blank=True, null=True)),
                ('easting', models.FloatField(blank=True, null=True)),
                ('zoom', models.SmallIntegerField(default=12)),
                ('media_caption', models.CharField(blank=True, max_length=100, null=True)),
                ('media_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('media_url', models.URLField(blank=True, max_length=400, null=True)),
                ('text_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('text_text', models.TextField(blank=True, null=True)),
                ('wikipedia_name', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SlideHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated from the text headline.', max_length=255, null=True, unique=True)),
                ('location_line', models.BooleanField(default=True)),
                ('media_caption', models.CharField(blank=True, max_length=100, null=True)),
                ('media_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('media_url', models.URLField(blank=True, max_length=300, null=True)),
                ('text_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('text_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='overview', max_length=20)),
                ('wikipedia_name', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Slidepack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_order', models.SmallIntegerField()),
                ('slide_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storymaps.slide')),
                ('slideheader_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storymaps.slideheader')),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='slideheader',
            field=models.ManyToManyField(related_name='slidepack_slide', through='storymaps.Slidepack', to='storymaps.SlideHeader'),
        ),
    ]
