# Generated by Django 3.2.1 on 2024-03-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('storymaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideheader',
            name='text_text',
        ),
        migrations.AddField(
            model_name='slideheader',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.post'),
        ),
    ]
