# Generated by Django 3.2.7 on 2022-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storymaps', '0002_alter_slide_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='wikipedia_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
