# Generated by Django 3.2.1 on 2024-02-16 14:53

# import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukheritage", "0002_alter_gdukalwaysopenland_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gduklistedbuildings",
            name="capturesca",
            field=models.CharField(
                blank=True, db_column="CaptureSca", max_length=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gduklistedbuildings",
            name="geometry",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gdukparksgardens",
            name="geometry",
            field=models.TextField(blank=True, null=True),
        ),
    ]
