# Generated by Django 3.2.1 on 2024-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukheritage', '0003_auto_20240216_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdukscheduledmonuments',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=11, null=True),
        ),
    ]
