# Generated by Django 3.2.1 on 2024-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukheritage', '0006_alter_gdukscheduledmonuments_capturesca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdukparksgardens',
            name='capturesca',
            field=models.CharField(blank=True, db_column='CaptureSca', max_length=15, null=True),
        ),
    ]
