# Generated by Django 3.1.6 on 2021-02-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=None, max_length=100)),
                ('wikislug', models.SlugField(default=None)),
                ('url', models.URLField(default=None)),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mvs.heritagesite', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryVehicleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvclass', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('wikislug', models.SlugField(blank=True, default=None, max_length=300, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Military Vehicle Classes',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='MVImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('notes', models.TextField(default=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mvs.heritagesite', verbose_name='Location')),
                ('mvclass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mvs.militaryvehicleclass', verbose_name='Military Vehicle Class')),
                ('visit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mvs.visit', verbose_name='Visit')),
            ],
        )
    ]
