# Generated by Django 3.2.1 on 2022-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvimage',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
