# Generated by Django 3.1.7 on 2021-03-20 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvs', '0002_auto_20210316_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mvbmimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvimages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mvbmimage',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='mvimages_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
