# Generated by Django 3.2.1 on 2021-05-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0003_auto_20210320_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
