# Generated by Django 3.2.1 on 2024-02-12 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.CharField(db_index=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid slug consisting of letters, numbers, apostrophes, commas, underscores, or hyphens.', regex="^[a-zA-Z0-9'_,-]+$")]),
        ),
        migrations.AlterField(
            model_name='route',
            name='wikipedia_slug',
            field=models.CharField(db_index=True, default=None, help_text='Enter a slug only if you wish to override that which will be autogenerated', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Enter a valid slug consisting of letters, numbers, apostrophes, commas, underscores, or hyphens.', regex="^[a-zA-Z0-9'_,-]+$")]),
        ),
        migrations.CreateModel(
            name='RouteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('date_opened', models.CharField(blank=True, max_length=10, null=True)),
                ('date_closed', models.CharField(blank=True, max_length=10, null=True)),
                ('date_opened_passenger', models.CharField(blank=True, max_length=10, null=True)),
                ('date_closed_passenger', models.CharField(blank=True, max_length=10, null=True)),
                ('route_fk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.route')),
            ],
            options={
                'verbose_name': 'Route Section',
                'verbose_name_plural': 'Route Sections',
            },
        ),
    ]
