# Generated by Django 3.2.1 on 2023-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
        migrations.AlterField(
            model_name='route',
            name='wikipedia_routemaps',
            field=models.ManyToManyField(blank=True, to='locations.RouteMap'),
        ),
    ]
