# Generated by Django 3.2.1 on 2022-11-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UkAdminBoundaries',
        ),
    ]
