# Generated by Django 3.2.1 on 2022-11-17 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_delete_ukadminboundaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkAdminBoundaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.CharField(blank=True, max_length=10, null=True)),
                ('ctyua19cd', models.CharField(blank=True, max_length=100, null=True)),
                ('ctyua19nm', models.CharField(blank=True, max_length=100, null=True)),
                ('ctyua19nmw', models.CharField(blank=True, max_length=100, null=True)),
                ('bng_e', models.FloatField(blank=True, null=True)),
                ('bng_n', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('st_areasha', models.FloatField(blank=True, null=True)),
                ('st_lengths', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'locations_UK_admin_boundaries',
                'managed': False,
            },
        ),
    ]
