# Generated by Django 3.2.1 on 2023-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_post_references'),
        ('locations', '0002_auto_20230325_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='references',
            field=models.ManyToManyField(blank=True, to='notes.Reference'),
        ),
    ]
