# Generated by Django 3.2.1 on 2022-11-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_ukadminboundaries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UkAdminBoundaries',
        ),
    ]
