# Generated by Django 3.2.1 on 2024-02-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20240213_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routesection',
            name='elr_fk',
        ),
        migrations.RemoveField(
            model_name='routesection',
            name='max_lat',
        ),
        migrations.RemoveField(
            model_name='routesection',
            name='max_lon',
        ),
        migrations.RemoveField(
            model_name='routesection',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='routesection',
            name='min_lon',
        ),
        migrations.CreateModel(
            name='RouteSectionELR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_lat', models.FloatField(blank=True, default=None, null=True)),
                ('min_lon', models.FloatField(blank=True, default=None, null=True)),
                ('max_lat', models.FloatField(blank=True, default=None, null=True)),
                ('max_lon', models.FloatField(blank=True, default=None, null=True)),
                ('elr_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.elr')),
                ('route_section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.routesection')),
            ],
            options={
                'verbose_name': 'ELR on a Route Section',
                'verbose_name_plural': 'ELRs on a Route Section',
            },
        ),
        migrations.AddField(
            model_name='routesection',
            name='elrs',
            field=models.ManyToManyField(blank=True, through='locations.RouteSectionELR', to='locations.ELR'),
        ),
    ]
