# Generated by Django 3.2.1 on 2023-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230325_1512'),
        ('locations', '0003_location_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_owneroperator',
            field=models.ManyToManyField(blank=True, to='companies.Company'),
        ),
    ]
