# Generated by Django 3.2.1 on 2023-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_route_route_owneroperator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='routegeoosm',
            options={'managed': False, 'verbose_name': 'OSM Route Geometry',
                     'verbose_name_plural': 'OSM Routes Geometries'},
        ),
    ]
