# Generated by Django 3.2.1 on 2022-11-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_ukadminboundaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.SlugField(blank=True, max_length=20, null=True)),
                ('itemLabel', models.CharField(default=None, max_length=400)),
                ('itemAltLabel', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
