# Generated by Django 3.2.1 on 2023-04-08 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20230407_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='elr_points',
            field=models.ManyToManyField(
                blank=True, related_name='elr_locations', through='locations.ELRLocation', to='locations.ELR'),
        ),
    ]
