# Generated by Django 3.2.1 on 2023-04-08 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20230408_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='elrlocation',
            name='distance',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='routegeoclosed',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326),
        ),
    ]
