# Generated by Django 3.2.1 on 2022-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_elr_itemaltlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elr',
            name='itemAltLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
