# Generated by Django 3.2.1 on 2022-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_elr_itemaltlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elr',
            name='item',
            field=models.SlugField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='elr',
            name='itemAltLabel',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
