# Generated by Django 3.2.1 on 2023-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20230408_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elrlocation',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
