# Generated by Django 3.2.1 on 2023-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_elrlocation_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elrlocation',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
