# Generated by Django 3.2.1 on 2022-11-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_elr_itemlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='elr_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.elr'),
        ),
    ]
