# Generated by Django 3.2.1 on 2023-04-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_elrlocation_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elrlocation',
            options={'verbose_name': "Engineer's Line Reference Location", 'verbose_name_plural': "Engineer's Line Reference Locations"},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_owneroperator',
            new_name='owneroperators',
        ),
    ]
