# Generated by Django 3.2.1 on 2023-04-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20230428_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='wikipedia_route_categories',
            new_name='wikipedia_categories',
        ),
    ]
