# Generated by Django 3.2.1 on 2022-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_locationevent_elr_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='codes',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='code_dates',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='date_closed',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='date_closed_to_steam',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='date_opened',
        ),
        migrations.AddField(
            model_name='depot',
            name='date_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='date_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='datefield_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='datefield_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
