# Generated by Django 3.2.1 on 2023-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_rename_wikipedia_route_categories_route_wikipedia_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='elrs',
            field=models.ManyToManyField(blank=True, to='locations.ELR'),
        ),
    ]
