# Generated by Django 3.2.1 on 2022-12-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20221128_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='disusedslug',
        ),
    ]
