# Generated by Django 3.2.1 on 2022-12-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_remove_location_disusedslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='elr_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.elr'),
        ),
    ]
