# Generated by Django 3.2.1 on 2023-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20230507_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='routelocation',
            name='linear_reference',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
