# Generated by Django 3.2.1 on 2023-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20230510_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='subgroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
