# Generated by Django 3.2.1 on 2022-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20221230_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='osm_node',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
