# Generated by Django 3.2.1 on 2023-01-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_alter_location_osm_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Depot', 'verbose_name_plural': 'Depots'},
        ),
        migrations.AlterModelOptions(
            name='elr',
            options={'verbose_name': "Engineer's Line Reference", 'verbose_name_plural': "Engineer's Line References"},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationevent',
            options={'verbose_name': 'Location Event', 'verbose_name_plural': 'Location Events'},
        ),
        migrations.AlterModelOptions(
            name='routecategory',
            options={'managed': True, 'verbose_name': 'Route Category', 'verbose_name_plural': 'Route Categories'},
        ),
        migrations.AlterModelOptions(
            name='routegeoclosed',
            options={'verbose_name': 'Closed Route Geometries', 'verbose_name_plural': 'Closed Routes Geometries'},
        ),
        migrations.AlterModelOptions(
            name='routegeoosm',
            options={'verbose_name': 'OSM Route Geometry', 'verbose_name_plural': 'OSM Routes Geometries'},
        ),
        migrations.AlterModelOptions(
            name='routegeoosmhistory',
            options={'managed': False, 'verbose_name': 'OSM History Route Geometry', 'verbose_name_plural': 'OSM History Routes Geometries'},
        ),
        migrations.AlterModelOptions(
            name='routelocation',
            options={'verbose_name': 'Route Location', 'verbose_name_plural': 'Route Locations'},
        ),
        migrations.AlterModelOptions(
            name='routemap',
            options={'managed': True, 'verbose_name': 'Route Map (Wikipedia)', 'verbose_name_plural': 'Route Maps (Wikipedia)'},
        ),
        migrations.AlterModelOptions(
            name='ukadminboundaries',
            options={'managed': False, 'verbose_name': 'UK Admin Area Geometry', 'verbose_name_plural': 'UK Admin Areas Geometries'},
        ),
    ]
