# Generated by Django 3.2.1 on 2023-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_auto_20230124_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
