# Generated by Django 3.2.1 on 2023-01-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_route_post_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='route',
            name='notes',
        ),
    ]
