# Generated by Django 3.2.1 on 2023-01-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_post_body'),
        ('locations', '0020_auto_20230129_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.post'),
        ),
    ]
